name: Sudha's Daily Commit
on:
  schedule:
    - cron: '0 3 * * *'  # 3:00 AM UTC = 08:30 AM IST
  workflow_dispatch:  # Allows manual trigger
permissions:
  contents: write  # Explicitly gives write permission to repository contents
jobs:
  commit:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper commit counting
    
    - name: Configure Git
      run: |
        git config --global user.name "SudhaSarraf"
        git config --global user.email "sudhasarraf217@gmail.com"
      shell: pwsh
    
    - name: Update or Create Commit Info File
      run: |
        $FILE = "commit_info.md"
        $CURRENT_DATE = "$(Get-Date -Format 'yyyy-MM-dd')"
        
        if (!(Test-Path $FILE)) {
          # Create new file with the first commit message
          "Hi, this is my 1st commit on $CURRENT_DATE." | Out-File -FilePath $FILE
        } else {
          # Update existing file
          $content = Get-Content $FILE -Raw
          
          # Extract current commit number
          $match = [regex]::Match($content, "Hi, this is my (\d+)(st|nd|rd|th) commit")
          if ($match.Success) {
            $currentCount = [int]$match.Groups[1].Value
            $nextCount = $currentCount + 1
            
            # Determine the correct ordinal suffix
            $suffix = "th"
            if ($nextCount % 100 -lt 11 -or $nextCount % 100 -gt 13) {
              switch ($nextCount % 10) {
                1 { $suffix = "st" }
                2 { $suffix = "nd" }
                3 { $suffix = "rd" }
              }
            }
            
            # Replace entire content with the new message
            "Hi, this is my ${nextCount}${suffix} commit on $CURRENT_DATE." | Out-File -FilePath $FILE
          } else {
            # If pattern not found, create with commit number 1
            "Hi, this is my 1st commit on $CURRENT_DATE." | Out-File -FilePath $FILE
          }
        }
        
        # Get the new commit number for the commit message
        $newContent = Get-Content $FILE -Raw
        $newMatch = [regex]::Match($newContent, "Hi, this is my (\d+)(st|nd|rd|th) commit")
        $commitNum = $newMatch.Groups[1].Value
        $suffix = $newMatch.Groups[2].Value
        
        # Commit and push changes
        git add .
        git commit -m "Updated to my ${commitNum}${suffix} commit on $CURRENT_DATE"
        git push "https://${{ github.token }}@github.com/${{ github.repository }}.git"
      shell: pwsh
